services:
  - type: web
    name: synapic
    env: node
    plan: free
    region: frankfurt
    buildCommand: "npm install"
    startCommand: "node app.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000